---
title: "Extravehicular Activities (EVAs)"
subtitle: An R Notebook by Brandi E. Markert
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=8, echo = FALSE, warning = FALSE, message = FALSE)
```

Examining EVAs over time, by country, and by vehicle. Using data downloaded from [Data.gov](https://catalog.data.gov/dataset/extra-vehicular-activity-eva-us-and-russia).

```{r}
# Openinng package libraries
library(tidyverse)
library(lubridate)
library(dplyr)
library(plotly)

# Importing data
EVA <- read.csv(file="C:\\Users\\brand\\OneDrive\\Documents\\R\\space-stuff\\Extra-vehicular_Activity__EVA__-_US_and_Russia.csv", header=TRUE, stringsAsFactors = FALSE)

# Changing 'Date' column to date class
EVA$Date <-  as.Date(EVA$Date, format = "%m/%d/%Y")
# Creating Year variable from Date
EVA$Year <- format(EVA$Date,"%Y")
# Converting 'Duration' from hours: minutes (string), to hours with decimal
EVA$Duration <- sapply(strsplit(EVA$Duration,":"),
  function(x) {
    x <- as.numeric(x)
    x[1]+x[2]/60
    }
)
EVA$Duration <- as.numeric(EVA$Duration)
# Color palette for country values
# color palette for the outcome
Countrycol<-c("USA"="#4575b4",  "Russia"="#f46d43")
```


Duration of EVAs varied over time.

```{r}
e <- ggplot(data=EVA, aes(x=Date, y=Duration, label=Crew)) +
  geom_point(mapping=aes(color=Country)) + labs(x="Date", y="Duration (hours)", 
                                                  title = "EVA Duration Over Time, By Country", 
                                                  caption = "Source: Data.gov") +
  scale_color_manual(values = Countrycol, name="Country")
ggplotly(e, tooltip=c("x","y","label"))
```


```{r}
s <- ggplot(data=subset(EVA, !is.na(EVA$Year)),  aes(x=Year, y=Duration, fill=Country)) +
  geom_col(na.rm = TRUE, position="stack") + 
    theme(axis.text.x = element_text(angle = 90), legend.position="right") +
    labs(title="Total Hours Spent in EVA Per Year, By Country", x="Year", y="Duration
         (hours)",
         caption = "Source: Data.gov") +
  scale_fill_manual(values = Countrycol, name="Country")
s
```


```{r}
p <- ggplot(EVA[EVA$Vehicle == "Apollo 16", ], aes(x=Date, y=Duration, label=Purpose)) +
  geom_point(mapping=aes(color=Crew)) + labs(x="Date", y="Duration (hours)", 
                                                  title = "EVAs During Apollo 16 Mission", 
                                                  caption = "Source: Data.gov") +
  scale_fill_brewer(palette="Dark2") +
  scale_x_date(date_labels="%m/%d/%Y")
ggplotly(p, tooltip="Purpose")
```
